Repository uab-cgds-worthey/rosalution, pull requests merged in 2023-03, with the labels that each got.

#45 Remove analysis from mongo script
  README.md
  etc/database/README.md
  etc/database/add-user.js
  etc/database/remove-analysis.sh
  etc/fixtures/import/C-PAM0074_2.json
Labels: enhancement

#50 Refactored analysis summaries for grouping genomic units more clearly
  backend/src/models/analysis.py
  backend/src/repository/analysis_collection.py
  frontend/src/components/AnalysisListing/AnalysisCard.vue
  frontend/src/components/DropDownMenu.vue
  frontend/src/views/AnalysisListingView.vue
  frontend/test/components/AnalysisListing/AnalysisCard.spec.js
Labels: bug

#52 Moved the transcript to be listed as apart of the variant in Analysis View
  etc/fixtures/import/C-PAM0084.json
  frontend/src/components/AnalysisView/GeneBox.vue
  system-tests/e2e/case_annotation_display_transcripts.cy.js
Labels: bug

#51 Adding new github action for generating the paper pdf
  .github/workflows/draft-paper.yml
Labels: enhancement

#46 Account view credentials
  frontend/src/main.js
  frontend/src/views/AccountView.vue
  frontend/src/views/UserInfoView.vue
  frontend/test/views/AccountView.spec.js
Labels: enhancement

#54 More remove analysis script
  etc/database/remove-analysis.sh
Labels: bug

#55 Annotation configuration update scripts
  etc/database/README.md
  etc/database/backup-database.sh
  etc/database/set-new-annotations-configuration.sh
Labels: enhancement

#56 Added Cpam0042 and Cpam0044 analysis json to etc/fixtures/import
  etc/fixtures/import/C-PAM0042.json
  etc/fixtures/import/C-PAM0044.json
Labels: enhancement

#57 Updated docker-compose.production.yml to use github docker registry
  docker-compose.production.yml
Labels: enhancement

#60 Revise Rosalution prerequisite documentation to indicate which parts of Node.JS and Python are needed
  README.md
Labels: documentation, enhancement

#62 Need to include the pull_request event trigger
  .github/workflows/common-static-analysis.yml
  .github/workflows/nodejs.yml
  .github/workflows/python.yml
  .github/workflows/system-tests.yml
Labels: bug
