Repository uab-cgds-worthey/rosalution, pull requests merged in 2023-01, with the labels that each got.

#21 Issue templates setup
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  CONTRIBUTING.md
Labels: documentation

#23 Automated system tests GitHub actions
  .github/workflows/system-tests.yml
Labels: enhancement

#24 Pull request template edits
  .github/pull_request_template.md
Labels: documentation

#26 Fix broken links in documentation
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
Labels: bug, documentation

#27 Virtual python environment in setup
  .gitignore
  README.md
  backend/README.md
  setup.sh
Labels: documentation, enhancement

#28 Updated the validation of the application settings for more intuitive validation failure
  backend/src/config.py
Labels: enhancement

#29 Add a footer to the website that credits CGDS
  frontend/src/App.vue
  frontend/src/components/AppFooter.vue
  frontend/src/main.js
Labels: enhancement

#30 added login information to the docs and added screenshots
  README.md
  docs/figures/logged-in.png
  docs/figures/login.png
Labels: documentation
