Repository uab-cgds-worthey/rosalution, pull requests merged in 2023-09, with the labels that each got.

#134 Added the state of the field section; and revised the figures
  docs/paper/analysis_annotations.jpg
  docs/paper/analysis_supporting_evidence.jpg
  paper.md
Labels: documentation

#136 Updating the readme to include a thumbnail and linkout to the demonst…
  README.md
Labels: documentation

#137 Updated the importer to include the new ACMG expected fields
  backend/src/core/phenotips_importer.py
  etc/fixtures/initial-seed/analyses.json
Labels: enhancement

#140 Updated the system tests workflow to use electron
  .github/workflows/system-tests.yml
Labels: bug

#139 [Frontend] Create a new discussion component to be displayed in an Analysis view
  .github/workflows/system-tests.yml
  frontend/src/components/AnalysisView/DiscussionSection.vue
  frontend/src/models/analyses.js
  frontend/src/styles/main.css
  frontend/src/styles/rosalution.css
  frontend/src/views/AnalysisView.vue
  frontend/test/components/AnalysisView/DiscussionSection.spec.js
  frontend/test/views/AnalysisView.spec.js
  paper.md
  system-tests/e2e/rosalution_analysis.cy.js
Labels: enhancement
