Repository uab-cgds-worthey/rosalution, pull requests merged in 2023-02, with the labels that each got.

#31 Production documentation
  README.md
Labels: documentation

#34 Rosalution version audit upgrades
  backend/.pylintrc
  backend/.yapfignore
  backend/requirements.txt
  backend/src/core/annotation_task.py
  backend/src/models/analysis.py
  frontend/package.json
  frontend/src/components/AnalysisListing/AnalysisListingHeader.vue
  frontend/src/components/AnalysisView/AnalysisViewHeader.vue
  frontend/src/components/AnnotationView/AnnotationViewHeader.vue
  frontend/src/components/RosalutionHeader.vue
  frontend/test/App.spec.js
  frontend/test/components/AnalysisListing/AnalysisCard.spec.js
  frontend/test/components/AnalysisListing/AnalysisListingHeader.spec.js
  frontend/test/components/AnalysisView/AnalysisViewHeader.spec.js
  frontend/test/components/AnalysisView/GeneBox.spec.js
  frontend/test/components/AnalysisView/SectionBox.spec.js
  frontend/test/components/AnnotationView/AnnotationViewHeader.spec.js
  frontend/test/components/RosalutionHeader.spec.js
  frontend/test/views/AnnotationView.spec.js
  frontend/test/views/LogoutView.spec.js
  frontend/yarn.lock
  system-tests/cypress.config.js
  system-tests/package.json
  system-tests/yarn.lock
Labels: enhancement

#36 Remove ROSALUTION_KEY from local development environment depdency
  .github/workflows/system-tests.yml
  README.md
  docker-compose.yml
  setup.sh
Labels: enhancement

#35 Feedback revisions from cgds dev team number 1 fans
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/workflows/system-tests.yml
  README.md
  backend/README.md
  frontend/README.md
  system-tests/support/commands.js
Labels: documentation

#37 Adding positional argument expansion to forward entrypoint arguments to backend uvicorn executable
  backend/etc/entrypoint-init.sh
  docker-compose.yml
Labels: bug

#38 Resolving why annotation is halting halfway for a new sample
  backend/src/core/annotation_task.py
  backend/tests/unit/core/test_annotation_task.py
  etc/fixtures/initial-seed/annotations-config.json
  setup.sh
Labels: bug

#33 Investigate oauth swagger
  .gitignore
  backend/.coveragerc
  backend/src/config.py
  backend/src/dependencies.py
  backend/src/models/user.py
  backend/src/repository/gridfs_bucket_collection.py
  backend/src/repository/user_collection.py
  backend/src/routers/analysis_router.py
  backend/src/routers/annotation_router.py
  backend/src/routers/auth_router.py
  backend/src/security/oauth2.py
  backend/src/security/security.py
  backend/tests/integration/test_analysis_routers.py
  backend/tests/integration/test_auth_routers.py
  backend/tests/unit/repository/test_gridfs_bucket_collection.py
  backend/tests/unit/repository/test_user_collection.py
  backend/tests/unit/security/test_security.py
  etc/fixtures/initial-seed/users.json
  frontend/src/components/AnalysisView/SectionBox.vue
  frontend/src/components/AnalysisView/SupplementalFormList.vue
  frontend/src/components/AnnotationView/AnnotationSection.vue
  frontend/src/components/RosalutionHeader.vue
  frontend/src/main.js
  frontend/src/models/analyses.js
  frontend/src/models/annotations.js
  frontend/src/requests.js
  frontend/src/stores/authStore.js
  frontend/src/views/AccountView.vue
  frontend/src/views/AnalysisView.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/UserInfoView.vue
  frontend/test/components/AnalysisView/SectionBox.spec.js
  frontend/test/stores/authStore.spec.js
  system-tests/cypress.config.js
  system-tests/e2e/case_supporting_evidence.cy.js
  system-tests/support/commands.js
Labels: enhancement

#32 script for Adding Users and Documentation for doing so
  README.md
  etc/fixtures/add_user.js
  etc/fixtures/example-adding-users.json
Labels: documentation, enhancement

#40 Documentation updates
  README.md
  docs/figures/rosalution-logins.png
  docs/figures/uploading-new-case.png
Labels: documentation

#41 Development debug route
  README.md
  backend/Dockerfile
  backend/etc/entrypoint-init.sh
  backend/src/main.py
  backend/src/routers/auth_router.py
  backend/src/routers/dev_router.py
  backend/tests/integration/test_auth_routers.py
  backend/tests/integration/test_dev_routers.py
  docker-compose.local-production.yml
  docker-compose.production.yml
  frontend/src/stores/authStore.js
  system-tests/support/commands.js
Labels: enhancement

#42 Backend cas auth writeup
  backend/README.md
Labels: documentation

#44 Documentation updates
  README.md
  backend/README.md
  frontend/README.md
Labels: documentation

#43 New User Information page for the frontend
  frontend/src/components/RosalutionHeader.vue
  frontend/src/main.js
  frontend/src/stores/authStore.js
  frontend/src/views/AccountView.vue
  frontend/test/components/RosalutionHeader.spec.js
  frontend/test/views/AccountView.spec.js
Labels: enhancement
