Repository uab-cgds-worthey/rosalution, pull requests merged in 2023-07, with the labels that each got.

#100 Update the backend documentation to describe how to run pytest with a manual ROSALUTION_KEY environment variable
  backend/README.md
  backend/tests/unit/core/test_annotation_task.py
Labels: documentation

#102 Phenotips importer update and corresponding Migration Script
  backend/src/core/phenotips_importer.py
  backend/src/routers/analysis_router.py
  backend/tests/unit/core/test_phenotips_importer.py
  etc/fixtures/initial-seed/analyses.json
  etc/fixtures/migrations/migrate-new-sections-phenotips-importer.js
  frontend/src/components/AnalysisView/SectionBox.vue
  frontend/src/components/AnalysisView/SectionText.vue
  system-tests/e2e/attach_analysis_section_image.cy.js
  system-tests/e2e/edit_case_analysis.cy.js
  system-tests/e2e/view_collapsible_case_information.cy.js
Labels: enhancement

#106 Updated the README to discuss how to visit the locally deployed application
  README.md
Labels: documentation

#108 Backend logging
  backend/README.md
  backend/logging.conf
  backend/src/core/annotation.py
  backend/src/core/annotation_logging.py
  backend/src/core/annotation_task.py
  backend/src/main.py
  backend/src/repository/genomic_unit_collection.py
  backend/src/routers/auth_router.py
  backend/tests/unit/core/test_annotate.py
  backend/tests/unit/core/test_annotation_task.py
Labels: enhancement

#110 Animal model icons and Updated annotation fixtures
  etc/fixtures/initial-seed/genomic-units.json
  frontend/src/assets/alliance-genome-logo.png
  frontend/src/assets/c-elegens-dataset-logo.png
  frontend/src/assets/mouse-dataset-logo.png
  frontend/src/assets/rat-dataset-logo.png
  frontend/src/assets/zebrafish-dataset-logo.png
  frontend/src/models/analyses.js
Labels: enhancement

#112 Backend production logging.conf
  backend/Dockerfile
Labels: bug
